# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbaack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=30)),
                ('contactEmail', models.EmailField(max_length=254, unique=True)),
                ('contactSubject', models.CharField(blank=True, max_length=30)),
                ('contactMessage', models.CharField(max_length=500)),
                ('ip_add', models.CharField(default='ABC', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
